baseURL = "https://render-hugo-demo.onrender.com"
languageCode = "en-us"
title = "On Render with love"
theme = "minimal"
googleAnalytics = ""

[params]
    author = "Dennis Irsigler"
    description = "a static Hugo site hosted on Render.com"
    githubUsername = "#"
    accent = ""
    showBorder = true
    backgroundColor = "white"
    font = 'neo-sans,"Inter var","system-ui","Helvetica Neue",Helvetica,Arial,sans-serif'
    highlight = true
    highlightStyle = "default"

[[menu.icon]]
    url = "https://render.com/"
    name = "fas fa-globe"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/render"
    name = "fab fa-twitter"
    weight = 2

[[menu.icon]]
    url = "https://github.com/dirsigler/render-hugo-demo"
    name = "fab fa-github"
    weight = 3
