version: "3.9"
services:
  server:
    container_name: render
    image: klakegg/hugo:0.91.2-ext-alpine
    entrypoint: hugo
    command: ["server", "--buildDrafts", "--watch"]
    volumes:
      - ".:/src"
    ports:
      - "1313:1313"
